# Generated by Django 4.0.4 on 2022-05-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.rental'),
            preserve_default=False,
        ),
    ]
