# Generated by Django 4.0.4 on 2022-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_options_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
