# Generated by Django 4.0.4 on 2022-05-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_rental_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation'),
        ),
    ]
