# Generated by Django 3.2.7 on 2022-05-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='previous',
        ),
    ]
